### ISSUE TITLE
Chrome Watcher Functionality Lost

### ISSUE THREAD

**Issue by tlcameron3** [ActivityWatch/aw-android#105]
Recently the Chrome watcher has stopped collecting data; my last datapoint is from 23 days ago. I am running Android 13. I wonder if this is due to some accessibility permission problem, as I have had that with other apps (Macrodroid), but ActivityWatch never asked for such permissions in the first place. I troubleshot, allowing ActivityWatch unrestricted battery usage, etc, and there was still no pull to the bucket. Was surprised the Chrome watcher worked in the first place, because I tried to get it running on the app before and it didn't seem to work; guess it was working in the background. No other app has this functionality for Android that I know of, so this service is very useful. However, it may be difficult (if related to accessibility) as Google further limits accessibility access on Android.

**Comment by ErikBjare** [comment]
Thanks for the report!

The Chrome watcher is in an early stage if development. Bugs like this are somewhat expected at this stage, but let's see what goes wrong.

I think you need to give ActivityWatch the Accessibility permission for it to work (given it uses `onAccessibilityEvent`). It's possible your device removed it for some reason.

**Comment by tlcameron3** [comment]
Magically, functionality is restored. Thank you!

**Comment by ErikBjare** [comment]
Was it the Accessibility permission? Or did it just randomly start working again?

**Comment by tlcameron3** [comment]
Yes it was
