### ISSUE TITLE
No action on log

### ISSUE THREAD

**Issue by alerque** [ActivityWatch/aw-android#18]
* Lineage-OS 16 on a OnePlus  5
* AW-Android v0.4.6

The first time I hit the "log" button it sent me off to grant permissions (which I did).

The second and all subsequent times it does nothing. In the "buckets" panel I only ever have a single entry dated the first launch of the app.

P.S. Really looking forward to this. I've tried a number of proprietary systems but they are so invasive I eventually gave up trusting them with my computer, phone, and web browser usage. There does not seem to be _any_ open source solution that covers all three areas that I can trust, and cobbling something together from different solutions for each platform was too much trouble and I gave it up. I'll be happy to have this working eventually!

**Comment by ErikBjare** [comment]
It actually does something, but you're right that there's no clear indication of it doing so! 

You can see for yourself: Open menu -> web UI -> raw data -> open the `aw-watcher-android-test` bucket -> you should see events.

I just deployed v0.4.8 which has some much needed improvements, including indications of logging when the button is clicked! It'll be live in an hour or two.

Happy to have you testing the Android app, but note that it's still very much a work in progress and I wouldn't rely on it for some time (but we're getting really close!).

**Comment by alerque** [comment]
You are correct. It does in fact have data in there! Thanks. I'll keep it logging and be looking forward to when I can do something useful with it. I'm not an Android programmer, but I'll keep an eye out for ways to contribute as well.
