### ISSUE TITLE
Put up beta on Google Play Store

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-android#2]

**Comment by ErikBjare** [comment]
I just set up the basics, just need to create a feature image and take two screenshots to start publishing internal test versions.

**Comment by ErikBjare** [comment]
Now just "Awaiting publication"

**Comment by ErikBjare** [comment]
Alright, done. Should be easy to publish newer versions when the time comes.

**Comment by johan-bjareholt** [comment]
Invite pls :)

**Comment by ErikBjare** [comment]
@johan-bjareholt Invited you to the developer console, and added you to the internal tester list, just use this link to register for the internal test: https://play.google.com/apps/internaltest/4699995929674093832

**Comment by Rakleed** [comment]
@ErikBjare Why didn't you publish the app as unreleased? For example, as did the [Swift Installer](https://play.google.com/store/apps/details?id=com.brit.swiftinstaller) and [Everdo](https://play.google.com/store/apps/details?id=net.everdo.everdo).

And do you plan to publish your application in [F-Droid](https://f-droid.org)?

**Comment by ErikBjare** [comment]
@Rakleed I did, but then I accidentally pushed one release to production, and there is no way to unpublish a production release, you can only upgrade it.
