### ISSUE TITLE
Add x86_64 version of library to build (Google requirement) 

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-android#20]
Apparently you need to supply a x86_64 binary for all apps on the Play Store before the deadline on the 1st of August if you want to be able to update your app: https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

According to a Google email I just received, this is apparently not the case for the Android app. It might just be as easy as to copy the library into a x86_64 folder.

**Comment by johan-bjareholt** [comment]
I'm looking at that link and can't see anything about x86_64, it only says 64-bit? (so I assume they mean aarch64/ARMv8)

**Comment by ErikBjare** [comment]
They write about it here: https://developer.android.com/distribute/best-practices/develop/64-bit
