### ISSUE TITLE
Getting issue while compiling android

### ISSUE THREAD

**Issue by iamjayantchauhan** [ActivityWatch/aw-android#31]
![Screenshot 2020-04-03 at 7 42 59 PM](https://user-images.githubusercontent.com/24570754/78369966-9ff6d080-75e3-11ea-8453-73b3df729761.png)

I followed all instructions to build the app But stuck here. Also, I have one more confusion about the application. Why we are loading from System? If there is an independent app, How it will work? 

`System.loadLibrary("aw_server")`

**Note: I am using Mac, So executed all thing as per Mac not as per Linux**

**Comment by ErikBjare** [comment]
What instructions did you follow? I didn't know we had any.

`System.loadLibrary` is used to load the aw-server-rust library. I've added some basic build instructions to the README, please let me know of any issues you might encounter.

**Comment by LDuncAndroid** [comment]
@iamjayantchauhan 
> Why we are loading from System? If there is an independent app, How it will work?

See the `System` API docs for an explanation. This line: `System.loadLibrary("aw_server")` loads the native library into the runtime.

https://developer.android.com/reference/java/lang/System#loadLibrary(java.lang.String)
