### ISSUE TITLE
Mobile uses old aw-server-rust that does not support queries 

### ISSUE THREAD

**Issue by 8bitgentleman** [ActivityWatch/aw-android#33]
[As discussed on the forum](https://forum.activitywatch.net/t/activity-watch-mobile-query-error/520/) the aw-server-rust version in the android app is an older version in which a bug prevents the use of queries. A simple query like this

```
events = query_bucket(find_bucket("aw-watcher-android-test"));
RETURN = events;
```

results in a parsing error

`ParsingError("(Some((Semi, Span { lo: 80, hi: 81, line: 3 })), \"expectedBool,Ident,If,LBrace,LBracket,LParen,Number,RBrace,Return,String, or end of file\")")`

**Comment by ErikBjare** [comment]
I'm working on updating significantly updating aw-android in https://github.com/ActivityWatch/aw-android/pull/32. Will hopefully have a new release soon.
