### ISSUE TITLE
View is reset on orientation change

### ISSUE THREAD

**Issue by nicolae-stroncea** [ActivityWatch/aw-android#46]
## To reproduce.

1. Start in default portrait orientation
2. Go to timeline.
3. Switch to horizontal orientation

**Results**: view is restarted to the default activity view.
**Expectations**: screen is rotated, and I'm still in the timeline

Looking online, the fix seems pretty straighforward, either adding a line in the manifest file `android:configChanges="orientation|screenSize"`[link](https://stackoverflow.com/questions/3329318/android-how-to-not-destroy-the-activity-when-i-rotate-the-device) or saving the instance in the activity lifecycle

**Comment by ErikBjare** [comment]
Thanks for reporting, should be fixed in https://github.com/ActivityWatch/aw-android/commit/c8f51e5565ac4c33623c4ffb510f7924a40e2994 (untested by me, though)
