### ISSUE TITLE
web-ui not working in API on github releases?

### ISSUE THREAD

**Issue by johan-bjareholt** [ActivityWatch/aw-android#55]
https://forum.activitywatch.net/t/android-app-cant-find-web-ui/888

**Comment by 2br-2b** [comment]
I'm the one having this issue. If there's anything I can do to help debug, let me know!

**Comment by 2br-2b** [comment]
if it helps, I'm running GrapheneOS on a Pixel 4XL.

**Comment by ErikBjare** [comment]
No idea what is going on here, but FWIW, I've installed the Android app from the GitHub releases APK on my Oculus Quest, and that works fine. 

The APK should be identical to the one on the Play Store, see:

https://github.com/ActivityWatch/aw-android/blob/66d5492f72cc47bbc6b2979c0031438d80e07392/.travis.yml#L55-L69

I'm sorry, but I'm really at a loss why it doesn't work for you :slightly_frowning_face:

**Comment by 2br-2b** [comment]
Does the app require any of Google's services?

**Comment by ErikBjare** [comment]
@2br-2b Nope, none.

**Comment by 2br-2b** [comment]
That's weird. Is there anywhere else I could install the apk from to try it? I am running GrapheneOS on a Pixel 4 XL, if that makes a difference

**Comment by ErikBjare** [comment]
@2br-2b You could try older releases, or in the worst case build it yourself.

It might be helpful if you could collect logs, there's a chance they contain something useful.

One of the things the app does is extract the web UI resources onto the filesystem for serving, this might be what goes wrong for you. Here's the code for it: https://github.com/ActivityWatch/aw-android/blob/66d5492f72cc47bbc6b2979c0031438d80e07392/mobile/src/main/java/net/activitywatch/android/AssetExtractor.kt#L11-L60

**Comment by ErikBjare** [comment]
Old issue.

The AssetExtractor code is now no longer used, as the webui is bundled with the library binaries instead.
