### ISSUE TITLE
Database locked error when doing rapid heartbeats

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-android#7]
I discovered this bug when building aw-android. I can provide more detail later (currently on my phone). 

Seems to be easily solvable by correctly handling Result unwrap, or waiting for the DB to "unlock". 

The simple workaround I used was to add a short pause between heartbeats (100ms, could probably go way lower).

**Comment by johan-bjareholt** [comment]
it's in the android/mod.rs file though, so unclear where to put it IMO as the acual fix should be done in aw-server-rust.

**Comment by johan-bjareholt** [comment]
I pushed the sqlite exclusive behavior change straight to master

https://github.com/ActivityWatch/aw-server-rust/commit/cae5604b7044979091d1448a1ec6b1cff92e5afa

**Comment by ErikBjare** [comment]
That would indeed break a lot in aw-android as I'm sometimes interacting with the server through the library and sometimes through the API. 

So I'd need two database connections if the server is to manage its own DB connection (unless they can be set up to share somehow, which they probably can...)

**Comment by johan-bjareholt** [comment]
An option would be to use rocket::local::Client just as we do in the api.rs unittests. Maybe not the most efficient solution, but would work very well.
On the other hand, you've gotten rocket to run now anyway so you could also just skip the bindings altogether.

**Comment by ErikBjare** [comment]
@johan-bjareholt I guess that's true, but there's something deeply satisfying with having direct access through the JNI. Shouldn't be too hard, so I gave it a go, but having issues with statics/lifetimes/etc in Rust, feel free to take a look and give it a shot: https://github.com/ActivityWatch/aw-server-rust/pull/19

**Comment by ErikBjare** [comment]
Fixed in https://github.com/ActivityWatch/aw-server-rust/pull/19
