### ISSUE TITLE
Crashes on launch (Android 12 GrapheneOS)

### ISSUE THREAD

**Issue by kromsam** [ActivityWatch/aw-android#78]
When I open the app, the following error message is shown:
http://127.0.0.1:5600/ bcan0y be loaded because

`net::ERR_CONNECTION_REFUSED`

I use the Play Store version of the app running the latest version of GrapheneOS (Android 12).

**Comment by ErikBjare** [comment]
Can you confirm if this still happens with v0.12.1b5?

Hopefully fixed.

**Comment by ErikBjare** [comment]
This specific crash on launch should be fixed. Closing.
