### ISSUE TITLE
Icons in settings not being rendered

### ISSUE THREAD

**Issue by ritamsaha00** [ActivityWatch/aw-android#80]
Device: Samsung S20 FE 5G
OS: Android 12 + One UI 4.1
App version: 0.10

![Screenshot_20221024-115740_ActivityWatch](https://user-images.githubusercontent.com/69363775/197461991-5a8e8dce-57a0-422b-9a1c-68fa1716d3c6.jpg)

As you can see, the icons in settings menu is not showing

**Comment by ErikBjare** [comment]
This is a known issue that will be fixed in the next version (whenever it gets released, might take a while...)
