### ISSUE TITLE
Newest version?

### ISSUE THREAD

**Issue by PeterKW** [ActivityWatch/aw-android#81]
https://apt.izzysoft.de/fdroid/index/apk/net.activitywatch.android

There seem to have been commits but no updates for quite a while? Are there any plans for the next release?

**Comment by OGoodness** [comment]
+1 would love to have access to a newer version without loading it myself

**Comment by ErikBjare** [comment]
Blocked due to https://github.com/ActivityWatch/aw-android/issues/94

**Comment by ErikBjare** [comment]
v0.12.0 is now released: https://github.com/ActivityWatch/aw-android/releases/v0.12.0

**Comment by PeterKW** [comment]
> v0.12.0 is now released: https://github.com/ActivityWatch/aw-android/releases/v0.12.0

Is that on fdroid?
