### ISSUE TITLE
InstrumentationRegistry is deprecated

### ISSUE THREAD

**Issue by XY-quantum** [ActivityWatch/aw-android#82]
In the line 25 of ExampleInstrumentedTest.kt file, `val appContext = InstrumentationRegistry.getTargetContext()` should be replaced by `val appContext = InstrumentationRegistry.getInstrumentation().getTargetContext()` cause of the 'InstrumentationRegistry' is deprecated in Java, otherwise, the gradle cannot be built.

**Comment by ErikBjare** [comment]
Will be fixed by: #85 / #88
