### ISSUE TITLE
This app was built for an older version of Android

### ISSUE THREAD

**Issue by jzheng23** [ActivityWatch/aw-android#93]
I am using the app for an academic research. Recently some participants got this "This app was built for an older version of Android" warning while trying to install ActivityWatch from Google Play Store. 
Two of the participants use Pixel 6a. 
Is this something easy to fix? I see the target SDK is already 33, so I am kind of confused.

**Comment by skewballfox** [comment]
Can Confirm this is the case on a pixel 6 running 13 (TQ2A.230505.002). [According to this SO post](https://stackoverflow.com/a/75515891/11019565), it should (hopefully) be as simple as updating the TargetSDKVersion.

**Comment by deniskonovalov64** [comment]
Good afternoon, may I know if there is any progress on this issue?

**Comment by ErikBjare** [comment]
Unfortunately blocked by the very tricky https://github.com/ActivityWatch/aw-android/issues/94

**Comment by ErikBjare** [comment]
Made some progress on #94

Hoping to get a new release out soon.

**Comment by ErikBjare** [comment]
I've gotten it running in an emulator now, after a few minor fixes. Trying to make a release.

**Comment by ErikBjare** [comment]
Made the release! https://github.com/ActivityWatch/aw-android/releases/tag/v0.12.0

Google rejected it though, due to a bunch of new rules. Will work on that.

**Comment by ErikBjare** [comment]
Google has now accepted it, and we're live with v0.12.1b5!

Here's the release announcement https://twitter.com/ActivityWatchIt/status/1712822712370942146?t=5SNng7qZOTSGcamBUU3Ifg&s=19

Thanks for reporting!
