### ISSUE TITLE
Unable to install 0.12 on Android 13

### ISSUE THREAD

**Issue by thelazyoxymoron** [ActivityWatch/aw-android#98]
When trying to install the apk, getting following error:

`INSTALL_FAILED_INVALID_APK: INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2`

Btw, I'm very excited for the latest release!

**Comment by ErikBjare** [comment]
Try the new one! (I wiped the previous broken release)

https://github.com/ActivityWatch/aw-android/releases/tag/v0.12.0

**Comment by ErikBjare** [comment]
Thanks, appreciate it!
